name: Azure GeoFoodTruck Live

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_USE_AZUREAD: true

    environment: az-dev

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install --omit=dev

    - name: Build the project
      run: npm run build
      env:
        GENERATE_SOURCEMAP: false

    - name: Save Build Output
      id: build-output
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./build
        overwrite: true
        retention-days: 1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      working-directory: ./tf/azure
      run: terraform init
      
    - name: Plan Terraform
      working-directory: ./tf/azure
      run: |
        terraform plan -out="../../.github/aztfplan.bin"
        terraform show -json "../../.github/aztfplan.bin" | jq  > "../../.github/aztfplan.json"
        sed -i -e 's/"primary_access_key": *"[^"]*"/"primary_access_key": "***"/' \
        -e 's/"secondary_access_key": *"[^"]*"/"secondary_access_key": "***"/' ../../.github/aztfplan.json

    - name: Apply Terraform
      working-directory: ./tf/azure
      run: |
        terraform apply -auto-approve "../../.github/aztfplan.bin"

    - uses: stefanzweifel/git-auto-commit-action@v5
      name: Commit Azure Terraform Plan
      with:
        commit_message: "Azure Terraform Plan"
        file_pattern: ".github/aztfplan.*"
        commit_user_name: fredmerlo
        commit_user_email: fredmerlo@gmail.com
        commit_author: fredmerlo <fredmerlo@gmail.com>
