name: Azure GeoFoodTruck Live

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_USE_AZUREAD: true

    environment: dev

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      working-directory: ./tf/azure
      run: terraform init
      
    - name: Plan Terraform
      working-directory: ./tf/azure
      run: |
        terraform plan -out="../../.github/aztfplan.bin"
        terraform show -json "../../.github/aztfplan.bin" | jq  > "../../.github/aztfplan.json"

    - name: Apply Terraform
      working-directory: ./tf/azure
      run: |
        terraform apply -auto-approve "../../.github/aztfplan.bin"
