name: GeoFoodTruck Live

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '.gitignore'
      - '.vscode/**'
      - '/tf/.plan/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: dev

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install --omit=dev

    - name: Build the project
      run: npm run build
      env:
        GENERATE_SOURCEMAP: false

    - name: Save Build Output
      id: build-output
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./build
        overwrite: true
        retention-days: 1

    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      working-directory: ./tf
      run: terraform init
      
    - name: Plan Terraform
      working-directory: ./tf
      run: |
        terraform plan -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" -out=".plan/tfplan.bin"
        terraform show -json ".plan/tfplan.bin" | jq  > ".plan/tfplan.json"

    - name: Apply Terraform
      working-directory: ./tf
      run: |
        terraform apply -auto-approve ".plan/tfplan.bin"
          echo '{"value":"https://'`terraform output -raw cloudfront_distribution_domain`'"}' | \
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.USE_VARS }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d @- https://api.github.com/repos/fredmerlo/geofoodtruck/actions/variables/BASE_URL

    - uses: stefanzweifel/git-auto-commit-action@v5
      name: Commit Terraform Plan
      with:
        commit_message: "Terraform Plan"
        file_pattern: "./.plan/**"
