name: Checkov IaC Scan

on:
  workflow_run:
    workflows: ["GeoFoodTruck Live"]
    types:
      - completed

  workflow_dispatch:

jobs:
  scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Scan
    runs-on: ubuntu-latest
    environment: test

    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Terraform Output
        uses: actions/download-artifact@v4
        with:
          name: terraform-output
          path: ./tf
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          file: ./tf/tfplan.json
          repo_root_for_plan_enrichment: ./tf
          deep_analysis: true
          soft_fail: true
          output_format: cli,sarif
          output_file_path: console,results.sarif
          log_level: DEBUG
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
