name: Checkov IaC Scan

on:
  workflow_run:
    workflows: ["GeoFoodTruck Live"]
    types:
      - completed

  workflow_dispatch:

jobs:
  scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Scan
    runs-on: ubuntu-latest
    environment: iac

    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Build Output
        uses: actions/download-artifact@v4
        with:
         name: build-output
         path: ./build
         run-id: ${{ github.event.workflow_run.id }}
         github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./tf
          file: .github/tfplan.json
          output_format: cli,sarif
          output_file_path: console,results.sarif
          config_file: .github/checkov.yaml
          download_external_modules: true
          enable_secrets_scan_all_files: true
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          REPO_ROOT_FOR_PLAN_ENRICHMENT: ./tf
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
