name: Checkov IaC Scan

on:
  workflow_run:
    workflows: ["GeoFoodTruck Live"]
    types:
      - completed

  workflow_dispatch:

jobs:
  scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Scan
    runs-on: ubuntu-latest
    environment: test

    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          file: ./tf/.plan/tfplan.json
          repo_root_for_plan_enrichment: ./tf
          deep_analysis: true
          soft_fail: true
          output_format: cli,sarif
          output_file_path: console,results.sarif
          config_file: ./.github/checkov.yaml
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
