name: Playwright Report

on:
  deployment_status:
    types:
      - success

jobs:
  container-test-job:
    if: github.event.deployment_status.state == 'success'
    name: Playwright Container
    runs-on: ubuntu-latest
    environment: test

    permissions:
      id-token: write
      contents: read

    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy

    steps:
    - name: Install AWS CLI
      working-directory: /github/home
      run: |
        curl https://geofoodtruck-test-report.s3.amazonaws.com/aws.tgz -o aws.tgz
        tar -xzf aws.tgz
        chmod +x ./aws/install
        ./aws/install

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run Playwright tests
      run: npx playwright test
      env:
        HOME: /root

    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Publish Playwright Report
      run: |
        aws s3 sync ./playwright-html-report s3://${{ secrets.APP_BUCKET_NAME }}
